### ISSUE TITLE
[MLS Spec change] Reorg move crypto forward (#567)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#1014]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/567

**Description of the changes**
> Depends on #566 
 > 
 > Moves the `Cryptographic Objects` and `Message Framing` sections ahead of `Ratchet Tree Operations`, to reduce forward references and have ratchet tree / key schedule / secret tree sections together.
 > 
 > <img width="495" alt="image" src="https://user-images.githubusercontent.com/75597/151605925-af25de8b-9361-4409-bd40-c9dafccc8038.png">
 >

**Comment by franziskuskiefer** [comment]
editorial
