### ISSUE TITLE
[MLS Spec change] Split out Secret Tree (#570)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#1017]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/570

**Description of the changes**
> Depends on #569 
 > 
 > As described in the protocol overview, the Secret Tree can be understood apart from the key schedule; the key schedule just provides the `encryption_secret` to become the root of the tree.  This PR pulls out the secret-tree-related subsections of the key schedule section into their own top-level section.
 > 
 > Best reviewed with `git diff reorg-move-kp-down --diff-algorithm=minimal` to show the diff against #569 
 > 
 > <img width="472" alt="image" src="https://user-images.githubusercontent.com/75597/151882712-66b6ba56-7688-4b47-9516-a19affe15336.png">
 >

**Comment by franziskuskiefer** [comment]
editorial
