### ISSUE TITLE
[MLS Spec change] Split the Group State section into Group Context and Transcript Hashes (#572)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#1019]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/572

**Description of the changes**
> This is the last of the reorg PRs.  Does what it says in the title.
 > 
 > <img width="482" alt="image" src="https://user-images.githubusercontent.com/75597/151904958-f1b7530e-2ef0-4ed0-93dd-b9e9db6bfcfc.png">
 >

**Comment by franziskuskiefer** [comment]
editorial
