### ISSUE TITLE
[MLS Spec change] Add message/mls MIME type registration (#581)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#1021]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/581

**Description of the changes**
> This is a minimal section for MIME type registration of message/mls. 
 > 
 > It assumes that PR #523 include wire_format in all MLS messages (making a format parameter unnecessary),
 > and that all messages have the MLS version number encoded (making a version parameter unnecessary).
 > 
 > These parameters can be added if needed.

**Comment by franziskuskiefer** [comment]
There's nothing to do here but I'll leave it open to make sure it's on the radar when working on #979.
