### ISSUE TITLE
[MLS Spec change] Clean up from KeyPackage/LeafNode split (#599)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#1026]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/599

**Description of the changes**
> While landing #587, I noticed that there were some dangling references left over from the KeyPackage/LeafNode split, e.g., to the "`parent_hash` extension" or `leaf_key_package`.  This PR cleans those up.

**Comment by franziskuskiefer** [comment]
No actionable items left on this change. Most of this has been covered as part of #819. Validation will be done in #1186 and #1210.
