### ISSUE TITLE
[MLS Spec change] Clean up LeafNode vs. KeyPackage (#612)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#1030]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/612

**Description of the changes**
> This PR picks up changes from #609 clarifying and cleaning up a few issues around LeafNode.

**Comment by franziskuskiefer** [comment]
Nothing to do here.
Validation will be done in #1186 and #1210
