### ISSUE TITLE
Stop using old treemath test vectors

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#104]
With the new test vectors in we should remove the old test vectors for treemath.

---

Tree math was updated in the MLS spec in #359 (PR in the mls repo) and maelstrom was updated accordingly in #102. Currently, we just skip the erroneous entries in the test vector that assume the old treemath. We should instead fix the test vector (and distribute it to the other implementors).

**Comment by raphaelrobert** [comment]
@franziskuskiefer is this fixed with the new KAT vectors for treemath?

**Comment by franziskuskiefer** [comment]
We should stop using the old test vectors I guess. (I'll update this issue.) The new test vectors should get into the implementation repo https://github.com/mlswg/mls-implementations/pull/35
