### ISSUE TITLE
ProtocolVersion review

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#1065]
- [x] #1073
 - [ ] Remove draft 11

**Comment by duesee** [comment]
Just to make sure: I can do ...

```diff
pub enum ProtocolVersion {
-    Reserved = 0,
    Mls10 = 1,
-    Mls10Draft11 = 200, // pre RFC version
}
```

... and fixup? Can we think of any reason we want to keep the other versions? Can't imagine any.

**Comment by duesee** [comment]
Figured that it should be okay and already made a PR.
