### ISSUE TITLE
Remove `labeler` workflow?

### ISSUE THREAD

**Issue by duesee** [openmls/openmls#1081]
How useful is the ...

```
This PR is so big! Please, split it 😊
```

... labeler?

I thought it was cute at first but it's kinda getting old :-) Sorry, labeler.

Do we know of instances where this message was actually helpful? Do we want to keep it?

Alternatives:

* Keep as is.
* Keep labeling but don't comment.

**Comment by franziskuskiefer** [comment]
It's useful because it tells you that your PR is too big. We'll keep it.
