### ISSUE TITLE
[Bug] MlsMessage deserialization is not the inverse of serialization

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#1134]
I came across this while working on #979. I won't fix this in the course of my current PR, but will instead do a follow up. Tracked in #979.

**Comment by duesee** [comment]
I just saw this and it remembered me that I had some changes lying around I wanted to contribute. The `duesee/issue_1134` branch has an extended version of the `mls_message_decode` fuzz target. I think it detects the issue you mention here. Maybe it's useful for further investigation. (And I also think we should maybe eagerly derive/implement `Arbitrary` and introduce structured fuzz-testing in the future.)

**Comment by kkohbrok** [comment]
Fixed by #1136.
