### ISSUE TITLE
Sanitize input

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#115]
Right now the implementation doesn't have a lot of checks against malformed input values, especially when processing messages from other members.

**Comment by franziskuskiefer** [comment]
Shall this become the issue for implementing everything in https://github.com/openmls/openmls/wiki/Message-validation ?

**Comment by raphaelrobert** [comment]
Definitely part of it. I think the main issue is #133 though.

**Comment by kkohbrok** [comment]
Syntactic validation is taken care of by the `tls_codec`.
