### ISSUE TITLE
Return new GroupInfo along with StagedCommit

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#1150]
Currently, the new GroupInfo is not accessible to applications when creating a `StageCommit`. Instead, the Commit needs to be merged first, which in turn requires a preliminary validation by the DS.

It should be possible to return the new `GroupInfo` along with the `StagedCommit` but needs some preliminary investigation.

**Comment by beltram** [comment]
For context [here](https://github.com/wireapp/openmls/pull/13) is a PR implementing this on a fork of openmls

**Comment by augustocdias** [comment]
Can you assign me this issue?
