### ISSUE TITLE
Drop keys from previous epochs

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#119]
Key package bundles must not be carried across epochs.

**Comment by kkohbrok** [comment]
@franziskuskiefer I'm trying to understand what the issue here is/was. Old `KeyPackageBundle`s should be dropped when a diff is merged. Does that suffice? Or are they still stored in the key store somewhere?

**Comment by franziskuskiefer** [comment]
Well the logic here changed a lot since this was filed. I suspect that we are good the way it is right now.
Can you describe the mechanism there that's used to achieve forward secrecy, i.e. where the key package bundle is dropped, in the wiki (or even better the book) and then close this?

**Comment by kkohbrok** [comment]
I wrote down the process here: https://openmls.tech/book/forward_secrecy.html
