### ISSUE TITLE
Take a GroupStore as input to MlsGroup API and take control of group state serialization and storage

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#1194]
If we store key material from within the API, there is a potential divergence between group state and key material in case the process crashes mid-commit merge. To make this more robust, we could take a group store (analogous to the key store) as input to make the transition safer.

**Comment by keks** [comment]
Is this resolved by the new Storage trait? It sounds a little like it could be, but I'm not sure.

**Comment by kkohbrok** [comment]
Yes, this is indeed resolved with the new storage trait.
