### ISSUE TITLE
Allow provisioning of new LeafNode from MlsGroup's `self_update`

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#1208]
`self_update` allows passing in an `encryption_key`, which is pretty useless from a consumer perspective and which will be removed with #1203. It would be useful, however, to pass in a full LeafNode, s.t. the consumer can change extensions, the credential, etc.

**Comment by raphaelrobert** [comment]
The scope is actually larger, we should have the same API for

 - self-updates
 - proposed self-updates
 - external commits.

It should be possible to set 
 - a new credential
 - the capabilities
 - the leaf node extensions

for the leaf node.
