### ISSUE TITLE
Allow to set RequiredCapabilities in the GroupConfig

### ISSUE THREAD

**Issue by augustocdias** [openmls/openmls#1213]
At the moment it is not possible to set the required capabilities in a group. Adding a setter in the `MlsGroupConfigBuilder` would enable that.

              Could you create a new issue for this and link it here?

_Originally posted by @kkohbrok in https://github.com/openmls/openmls/pull/1211#discussion_r1082188572_

**Comment by kkohbrok** [comment]
This was fixed by #1473.
