### ISSUE TITLE
ci: Fix coverage

### ISSUE THREAD

**Issue by duesee** [openmls/openmls#1223]
```
cargo-tarpaulin: Couldn't find a release tarball containing binaries for latest.
```

**Comment by franziskuskiefer** [comment]
The action is unmaintained and broken. We have to move to something else.

**Comment by duesee** [comment]
Version 0.15.0 seems to work? https://github.com/openmls/openmls/actions/runs/4013997459/jobs/6893985258 Could we merge this to qickly unblock the PR workflows? I can make a follow-up soon?

**Comment by duesee** [comment]
Ah, I was glad too early: "Error: "Failed to get test coverage! Error: Failed to run tests: Error: Timed out waiting for test response"

I will see how to fix this.

**Comment by duesee** [comment]
I opened #1230 to track the replacement of unmaintained GitHub actions.
