### ISSUE TITLE
Adapt public API to new framing

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#1326]
Since the message framing now also includes `Welcome`, `KeyPackage` and `GroupInfo` the public API should be adapted accordingly.

 - [ ] Welcome (`new_from_welcome`)
 - [ ] KeyPackage
 - [ ] GroupInfo

**Comment by keks** [comment]
I have been looking for places that would need to be changed. For `Welcome`, `new_from_welcome` is the only one I could find. There are a few functions returning a `GroupInfo`:

 -[`join_by_external_commit`](https://github.com/openmls/openmls/blob/main/openmls/src/group/mls_group/creation.rs#L185-L193)
 - [`add_members`](https://github.com/openmls/openmls/blob/main/openmls/src/group/mls_group/membership.rs#L32-L37)
 - [`commit_to_pending_proposals`](https://github.com/openmls/openmls/blob/main/openmls/src/group/mls_group/processing.rs#L84-L91)
 - [`self_update`](https://github.com/openmls/openmls/blob/main/openmls/src/group/mls_group/updates.rs#L24-L31)

We could return an `MlsMessage` here, as well.

I am not sure about `KeyPackage`. There are a few functions that use and produce this, but intuitively I would say it has a more tangible meaning on its own. IIRC it can also be transferred out-of-band, is that correct? Maybe it makes sense to keep it as-is, but I'm not sure.

I can take a stab at this tomorrow.

cc @franziskuskiefer

**Comment by franziskuskiefer** [comment]
The current APIs don't allow getting the `GroupInfo` for inspection prior to creating the group. This makes it impossible to check the tree when the ratchet tree extension is used, without first creating the group.

**Comment by keks** [comment]
Okay, I see. I can just make the change to `new_from_welcome` now and then look into the way `GroupInfo` is used and what other options we have to make that information accessible while still returning an `MlsMessage` -- and whether that change would be worthwhile.
