### ISSUE TITLE
Creating KeyPackage Lifetime panics on wasm32-unknown-unknown

### ISSUE THREAD

**Issue by hamza1311** [openmls/openmls#1421]
**Describe the bug**
Creating KeyPackage Lifetime panics on wasm32-unknown-unknown as `SystemTime` is not available on this target:
https://github.com/openmls/openmls/blob/837c7a99b46b1d8090551da195c4f56c183af238/openmls/src/key_packages/lifetime.rs#L51-L54

**To Reproduce**
1. Call https://docs.rs/openmls/latest/openmls/key_packages/struct.Lifetime.html#method.new
2. See error

**Expected behavior**
Work correctly

**Actual behavior**
Panic
```
        panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:31:9
```

**Platform (please complete the following information):**

 - OS & OS version: wasm-pack test (irrelevant for this)
 - Architecture [e.g. x86_64] `wasm32-unknown-unknown`
 - Version [e.g. v0.2] 0.5

**Comment by franziskuskiefer** [comment]
wasm is not supported right now. See #487.

**Comment by hamza1311** [comment]
Hi, I understand it's not supported. I created a PR to fix this issue, which I would appreciate if it were merged. Other than that, I have not encountered any issues running it in browser
