### ISSUE TITLE
Support for custom credential types

### ISSUE THREAD

**Issue by Bren2010** [openmls/openmls#1459]
**Is your feature request related to a problem? Please describe.**

MLS has a private-use space for types of credentials that are application-specific. OpenMLS doesn't support letting applications use this space at all.

**Describe the solution you'd like**

OpenMLS should implement support for custom credential types. These credentials would be implemented by the application, and follow a trait implementation of serialization / verification / etc. OpenMLS would ensure that the verification method is called where necessary.

**Describe alternatives you've considered**

Currently when trying to implement an application-specific credential, the best option is to just shove a bunch of data into a BasicCredential and try to do all of the necessary verification in the application. This introduces a substantial amount of complexity and potential for bugs.

**Additional context**

**Comment by franziskuskiefer** [comment]
Fixing this should also address #134.

I agree that OpenMLS should support more credentials. OpenMLS itself doesn't need to know much about the credential. For historical reasons it did know more than necessary. Rewriting credentials to be opaque for OpenMLS would allow custom credentials as well.
