### ISSUE TITLE
[Bug] `VerifiedStruct` doesn't achieve what it appears to be attempting

### ISSUE THREAD

**Issue by keks** [openmls/openmls#1465]
[`VerifiedStruct`](https://github.com/openmls/openmls/blob/main/openmls/src/ciphersuite/signable.rs#L58-L80) has  an associated type  `SealingType` that the caller should not be able to construct, so they are not able to call the `from_verifiable` function. However, since `SealingType` has a constraint to implement `Default` (which it needs; it is used by the `verify` method of [`Verifiable`](https://github.com/openmls/openmls/blob/main/openmls/src/ciphersuite/signable.rs#L129-L170)), the user can trivially construct it, too.

I briefly discussed this with @franziskuskiefer. We believe the best way to fix this is to just make the `VerifiedStruct` trait private. Since this is mostly an internal tool for limiting access, this should be fine. It seems the only other way would be to do it (edit: i mean the conversion between the source type and target struct here) inside the `verify` method, which would require the implementation of the `Verifiable` trait to have full visibility into the target struct.

**Comment by kkohbrok** [comment]
Hm. I totally missed that default allows you to construct `SealingType` even though it's hidden away in a non-visible module. We could make the trait private, but the original idea was not just to enforce verification outside of OpenMLS, but also on a per-module basis inside of OpenMLS. Ideally, I should be able to define a verifiable struct in a module and then ensure that outside of that module, verification has to take place via `verify` (and not `from_verifiable`). Maybe that's not possible in the end?

**Comment by keks** [comment]
I just reviewed all (I think) the implementors of `Verifiable` and `VerifiedStruct`, and as far as I can tell all pairs of implementations live in a single module each. So the functions have full visibility into each of the structs, and we could just make it a simple trait implementation.

I guess the question is whether we can require this to always be the case. My intuition is "probably yes".

If we do this, I think there are a few open design questions here:

- That trait implementation would basically be `TryInto` that returns a validation error. I don't have strong opinions whether a this should be a separate trait -- I think it might, both to signal the semantics and in order to be able to validate without converting.
- We could also have an empty marker trait for the verified type, so we can constrain to verified inputs in other places.
  ```rust
  trait Verified {}
  ```
- If it is a separate trait, should the destination type be a generic argument to the trait or should it be an associated type? I think this probably hinges on whether a single source type can have more than one destination types. If so, it can't be an associated type. Either way, we could constrain that type to having to implement that marker trait.
  ```rust
  trait Verifiable<T: Verified> {
    fn verify(self) -> T;
    fn verify_only(&self) -> bool;
  }
  ```
  or
  ```rust
  trait Verifiable {
    type Output: Verified;
    fn verify(self) -> Self::Output;
    fn verify_only(&self) -> bool;
  }
  ```

We can then have a private function `from_unverified` on the verified type, and call that from the `verify` function in the trait implementation.

**Comment by kkohbrok** [comment]
I think I agree with all the things you're proposing, but I'm not sure I fully understand the approach in its entirety. Can you maybe provide a small example, or create a mock PR that outlines the resulting traits and structure?

**Comment by keks** [comment]
Sure! Consider the implementation at https://github.com/openmls/openmls/blob/main/openmls/src/messages/group_info.rs#L264-L287. Instead, we could have


```rust
impl Verifiable for VerifiableGroupInfo {
    type Verified = GroupInfo;

    fn unsigned_payload(&self) -> Result<Vec<u8>, tls_codec::Error> {
        self.payload.tls_serialize_detached()
    }

    fn signature(&self) -> &Signature {
        &self.signature
    }

    fn label(&self) -> &str {
        SIGNATURE_GROUP_INFO_LABEL
    }

    fn verify(self) -> Result<Self::Verified, SignatureError> {
        self.verify_no_out(&self)?;
        Ok(GroupInfo::from_verifiable(self))
}

// Note: private and not a trait impl, i.e. not accessible from outside this module
impl GroupInfo {
    fn from_verifiable(v: VerifiableGroupInfo) -> Self {
        Self {
            payload: v.payload,
            signature: v.signature,
        }
    }
}

// marks that GroupInfo is verified
impl Verified for GroupInfo {}
```

This uses the trait I suggested above, with the exception that I previously forgot to make the output of `verify` a `Result`. I think the main difference is that we manually implement `verify`, which is annoying but I don't think there is a way around that.

**Comment by kkohbrok** [comment]
Right, I think I just wasn't sure how you had envisioned the implementation of `verify`. I agree, that the manual implementation is annoying, but it's certainly preferable to the current design which, as you rightly point out, doesn't work as intended.

In any case, that solution looks good to me as a replacement of the current design.
