### ISSUE TITLE
API: Make credential validation more convenient

### ISSUE THREAD

**Issue by keks** [openmls/openmls#1469]
Difficult to get credential validation right. API needs to be improved here

**Comment by keks** [comment]
Draft: https://github.com/openmls/openmls/tree/keks/leaf_node_staged_commit_iterator

**Comment by danielkeller** [comment]
From the spec

>  A member's credential is said to be _validated with the AS_ when the AS verifies that the credential's presented identifiers are correctly associated with the `signature_key` field in the member's LeafNode...

But this API doesn't return the signature key. Doesn't that mean application can't validate the credentials?

**Comment by franziskuskiefer** [comment]
> But this API doesn't return the signature key. Doesn't that mean application can't validate the credentials?

This issue was about credential verification.
You can get the signature key from the leaf node. The committers leaf node is in the staged commit `update_path_leaf_node()`, and the newly added signature keys are in `add_proposals()` of a staged commit.

Are missing any other function?
