### ISSUE TITLE
Testbed for wasm binary size

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#1489]
- [ ] prepare a testbed
  - [x] shell script to build with different configurations
  - [x] way to measure size
  - [ ] minimal API to do common operations

**Comment by keks** [comment]
This is being worked on on the branch `keks/wasm-bench`. Next step is building minimal bindings to drive an `MlsGroup`, and all the the pieces needed to do that.

**Comment by franziskuskiefer** [comment]
- [ ] Fix the test
- [ ] Get it on CI
