### ISSUE TITLE
Take `Welcome` as input to `new_from_welcome`

### ISSUE THREAD

**Issue by josephlukefahr** [openmls/openmls#1519]
I'm open to feedback on my use of your API, BTW.  Thanks for all the hard work!

**Is your feature request related to a problem? Please describe.**
Yes -- Previously, the `MlsGroup::new_from_welcome` method took `Welcome` as input, which allowed for an elegant (IMHO) procedure for de-framing an arbitrary `MlsMessageIn`.  See additional context for my de-framing implementation.  877607c interrupted that.

**Describe the solution you'd like**
I'd like to be able to call a method that stages a new group directly from a `Welcome` message.  This can be in addition to the current `StagedWelcome::new_from_welcome` method that takes in a `MlsMessageIn`; don't want to interfere with your progress.

**Describe alternatives you've considered**
Another alternative would be to make a `Welcome` message convertible back into `MlsMessageIn`, although this conversion is not implemented.  Since I'm not an OpenMLS expert and just trying to follow along, that's the only alternative I see.

**Additional context**
Here are snippets showing my de-framing procedure (before #1506):
```rust
    pub fn process(&mut self, msg_in: Vec<u8>, should_attempt_join: bool) -> SimpleMlsProcessingOutput {
        // un-byte-vector the message and then process message contents
        use openmls::prelude::TlsDeserializeTrait;
        self.process_mlsmsg(
            openmls::framing::MlsMessageIn::tls_deserialize_exact(msg_in)?,
            should_attempt_join,
        )
    }

    fn process_mlsmsg(
        &mut self,
        mlsmsg_in: openmls::framing::MlsMessageIn,
        should_attempt_join: bool,
    ) -> SimpleMlsProcessingOutput {
        match mlsmsg_in.extract() {
            // incoming keypackage
            openmls::framing::MlsMessageBodyIn::KeyPackage(keypkg_in) => {
                self.process_keypkg(keypkg_in)
            }
            // incoming welcome message
            openmls::framing::MlsMessageBodyIn::Welcome(welcome_in) => {
                self.process_welcome(welcome_in)
            }
            // private message, to be further processed as protocolmessage
            openmls::framing::MlsMessageBodyIn::PrivateMessage(privmsg_in) => self
                .process_protomsg(
                    openmls::framing::ProtocolMessage::from(privmsg_in),
                    should_attempt_join,
                ),
            // public message, to be further processed as protocolmessage
            openmls::framing::MlsMessageBodyIn::PublicMessage(pubmsg_in) => self.process_protomsg(
                openmls::framing::ProtocolMessage::from(pubmsg_in),
                should_attempt_join,
            ),
            // group info
            openmls::framing::MlsMessageBodyIn::GroupInfo(grpinfo_in) => {
                self.process_grpinfo(grpinfo_in)
            }
        }
    }

    fn process_welcome(
        &mut self,
        welcome_in: openmls::messages::Welcome,
    ) -> SimpleMlsProcessingOutput {
        log::debug!("((( process welcome )))");
        let new_group = openmls::group::MlsGroup::new_from_welcome(
            &self.backend,
            self.group_create_config.join_config(),
            welcome_in,
            None,
        )?;
        log::debug!("{:?}", new_group);
        self.groups.insert(new_group.group_id().clone(), new_group);
        Ok((None, None, None))
    }
```

**Comment by raphaelrobert** [comment]
This was indeed recently changed in #1506 and it is not aligned with the rest of the API as you correctly point out. I'd be in favor of reverting [that change](https://github.com/openmls/openmls/commit/877607ca75a77cd7afbd057da40b352fad269bdc) as a simple measure. We should not have two ways to process Welcome messages.

**Comment by josephlukefahr** [comment]
Point taken about not having two ways to process Welcome messages.  Also, there are other changes in #1506 that would need to be reverted (e.g. in 6956c3d).  Do y'all still think the issue is valid?

**Comment by josephlukefahr** [comment]
Roger that.  I'll get back to work on a PR for this issue.

**Comment by kkohbrok** [comment]
@josephlukefahr are you still planning on writing a PR? If not, I'd be happy to pick this up.

**Comment by josephlukefahr** [comment]
> @josephlukefahr are you still planning on writing a PR? If not, I'd be happy to pick this up.

I am but have been bogged down with other stuff.  My plan is to have it ready for review by end of this week (3/15/2024); feel free to knock it out sooner.
