### ISSUE TITLE
v0.6 release

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#1613]
- [x] cleanup
- [x] release notes
- [x] https://github.com/openmls/blog/pull/9
- [x] do the release
  - [x] #1652 
- [x] [release the book](https://github.com/openmls/book/actions/workflows/gh-pages.yml)

---

- #1626
- #1627
- #1628
- #1630 
- #1634 
- #1633 
- #1632 
- #1636

**Comment by karthikbhargavan** [comment]
Ready for release, someone with permissions needs to push the button.

**Comment by raphaelrobert** [comment]
We still want to remove `SerializedMlsGroup` before we release as it confuses folks

**Comment by franziskuskiefer** [comment]
[v0.6-pre.3](https://crates.io/crates/openmls/0.6.0-pre.3) is out. If we don't find any issues with this, we'll publish v0.6 in a week.
