### ISSUE TITLE
HPKE error

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#172]
It seems there's yet another error similar to #162, except that this time `hpke.open()` throws `OpenError`.

**Comment by franziskuskiefer** [comment]
What's the error you are seeing and what code triggers it?

**Comment by franziskuskiefer** [comment]
Ah, there's actually a ToDo in HPKE that I didn't fix yet that will probably cause this (it should appear randomly).

**Comment by franziskuskiefer** [comment]
This should be fixed in HPKE now. Please close unless you see an issue again.

**Comment by raphaelrobert** [comment]
I created #180 to test this.

**Comment by raphaelrobert** [comment]
Was fixed in #197.
