### ISSUE TITLE
Implement GroupContext extensions

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#186]
The `GroupContext` is missing the `extensions` field. The corresponding handling of extensions within a group is also missing.

cc #32

**Comment by kkohbrok** [comment]
This seems to be solved, as `GroupContext` now has an `extensions` field in `main`. Regarding the handling: To my knowledge, there's currently no extension that goes into the `GroupContext` (see https://github.com/mlswg/mls-protocol/pull/464 and https://messaginglayersecurity.rocks/mls-protocol/draft-ietf-mls-protocol.html#section-16.2).

**Comment by franziskuskiefer** [comment]
Well I guess I don't understand what `extensions` in the `GroupContext` are supposed to be and why they exist in the first place. But we currently hard code it to an empty vector. So if there were extensions, we'd have to implement them (there are also TODOs in the code).
