### ISSUE TITLE
External Commits

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#192]
https://github.com/mlswg/mls-protocol/pull/406

- [ ]  #542

**Comment by franziskuskiefer** [comment]
@raphaelrobert what's the state of this? Are you working on it? We need at least the structs in for the key schedule test vectors #326.

**Comment by raphaelrobert** [comment]
I can tackle that next if we need it for test vectors.

**Comment by franziskuskiefer** [comment]
From what I can see I need at least the `PublicGroupState` (actually `external_pub`) for the key schedule test vectors.
