### ISSUE TITLE
Codec cleanup

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#207]
Quite a few structs implement `Codec` although they don't have to. Two examples are `MlsGroup` and `EpochSecrets`.

I think (or I hope) that everything that needs codec either because it goes over the wire, it gets encrypted or it gets signed will make tests fail if a relevant `Codec` is missing.

**Comment by kkohbrok** [comment]
I believe this was solved in #203.

**Comment by kkohbrok** [comment]
I was wrong. There are still some unnecessary `encode` functions, for example for `EpochSecrets`.

**Comment by franziskuskiefer** [comment]
@kkohbrok I guess we can close this by now?

**Comment by kkohbrok** [comment]
Yup, this seems to be quite the relic.
