### ISSUE TITLE
Agile Credentials

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#21]
`Credential` can currently only handle basic credentials of type ed25519. We need to

- [x] Make `Credential` handle basic and x509 credentials (x509 should just panic for now)
- [x] Make `BasicCredential` know its key type for use outside of MLS
- [x] Make the `ciphersuite` in the `Identity` play nicely with the key type of the `BasicCredential`
- [x] Implement P256 basic credentials

**Comment by raphaelrobert** [comment]
I think this is all done. 

@franziskuskiefer feel free to close this if you agree.
