### ISSUE TITLE
Define a keystore

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#214]
It would be nice to have a generic keystore in place to handle KeyPackages and CredentialBundles

**Comment by franziskuskiefer** [comment]
@kkohbrok can you update this with what we have and we still need. I think there might also be more issues around this that should get linked and cleaned up.

**Comment by kkohbrok** [comment]
Ah, at some point I created #337, because I was not aware of this issue. Should I use this one, or the other one? #337 would also have to be updated.

**Comment by franziskuskiefer** [comment]
Closing in favour of #337.
