### ISSUE TITLE
Make MlsGroup private

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#215]
The `MlsGroup` API should be considered hazmat and should only be used by experienced consumers that want to implement a lot of the basic MLS logic that's not part of the standard themselves. The managed group should be the entry point for most users of the library as exposes a safe API.

**Comment by franziskuskiefer** [comment]
v0.4 will have put the `MlsGroup` behind a feature flag. It will not be officially supported.

**Comment by raphaelrobert** [comment]
This was fixed by #646.
