### ISSUE TITLE
Create testing framework for managed group API

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#219]
It would be useful to have a testing framework for the group API similar to the existing one for the low-level API. That would make testing of more complex cases easier and it should also be relatively easy to do.

**Comment by franziskuskiefer** [comment]
Collecting a couple follow up items here. Please move to a separate issue when you're done:
* Make cipher suite support more variable
* Allow using `group_config` and `public_tree` from `Welcome` message
* Allow delivering `public_tree` out of band

Can we try to get [these scenarios](https://github.com/mlswg/mls-implementations/blob/master/test-scenarios.md) implemented with the framework (follow-up)?
