### ISSUE TITLE
Don't derive Debug for secrets

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#247]
Let's not derive `Debug` for keys and secrets but only when people really know what they are doing.
`Debug` formatting should only print `***` for secrets and keys (private parts) by default and only print the key if an environment variable like `OPENMLS_PRINT_KEYS` is set.

**Comment by raphaelrobert** [comment]
This is implemented for `Secret` since #1277 and HPKE private keys use `SecretVLBytes`. There's also the `crypto-debug` feature that derives `Debug` on things like `AeadKey`.
