### ISSUE TITLE
[MLS Spec change] Groupcontext as context

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#287]
**Description of the changes**
Aligns the MLS key schedule more with the TLS key schedule

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/427

**Comment by franziskuskiefer** [comment]
@raphaelrobert this appears to be resolved with #293. Can you verify and close?

**Comment by raphaelrobert** [comment]
Yes, this fixed now.
