### ISSUE TITLE
[Bug] Trim the tree after removal

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#302]
**Describe the bug**
We currently only trim the tree when adding nodes

**Expected behavior**
The tree should also be trimmed when removing nodes.

**Comment by raphaelrobert** [comment]
This is now mentioned in https://github.com/mlswg/mls-protocol/issues/459.

**Comment by raphaelrobert** [comment]
And the spec is fixed in https://github.com/mlswg/mls-protocol/pull/461

**Comment by kkohbrok** [comment]
Fixed in spec and code: Closing.
