### ISSUE TITLE
[Bug] Faulty comparison in welcome message tests

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#304]
**Describe the bug**
There's an faulty comparison in the `test_welcome_message` [macro](https://github.com/openmls/openmls/blob/main/src/messages/test_welcome.rs#L71).

**To Reproduce**
Uncomment the check and build.

**Expected behavior**
The build should go through.

**Actual behavior**
The build quits with an error.

**Platform (please complete the following information):**
All

**Additional context**
None

**Comment by franziskuskiefer** [comment]
What is the error? Works fine for me locally and on CI.

**Comment by raphaelrobert** [comment]
Line 71: `assert_eq!(secret.key_package_hash, secret.key_package_hash);`

This compares the same values so it's always true. I couldn't figure out from the context what it is supposed to compare `secret.key_package_hash` against.

Not sure if I have a newer Rust version, or if clippy is complaining about this.
