### ISSUE TITLE
[Bug] Unable to build

### ISSUE THREAD

**Issue by t-900-a** [openmls/openmls#314]
**Describe the bug**

could not compile openmls

**To Reproduce**

git clone https://github.com/openmls/openmls.git
cd openmls/
sudo apt-get install cargo
cargo build

**Expected behavior**

build successfully
**Actual behavior**

> error[E0010]: allocations are not allowed in statics
   --> src/ciphersuite/mod.rs:154:47
    |
154 | static EMPTY_SECRET: Secret = Secret { value: vec![] };
    |                                               ^^^^^^ allocation not allowed in statics
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0019]: static contains unimplemented expression type
   --> src/ciphersuite/mod.rs:154:47
    |
154 | static EMPTY_SECRET: Secret = Secret { value: vec![] };
    |                                               ^^^^^^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: calls in statics are limited to constant functions, tuple structs and tuple variants
   --> src/ciphersuite/mod.rs:154:47
    |
154 | static EMPTY_SECRET: Secret = Secret { value: vec![] };
    |                                               ^^^^^^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0010, E0015, E0019.
For more information about an error, try `rustc --explain E0010`.
error: could not compile `openmls`.

**Screenshots or debug log**

**Platform (please complete the following information):**

ubuntu 20.10
**Additional context**

**Comment by raphaelrobert** [comment]
What version of the rust compiler do you use? I tried it with both `stable 1.49` and `nightly 1.50` on macOS and it worked.

For better control over rust updates you might want to use [rustup](https://rustup.rs) instead of installing cargo through apt.

**Comment by t-900-a** [comment]
that works thank you
