### ISSUE TITLE
[Feature request] Default ManagedGroupConfig

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#316]
In the tests, we currently have a `default_callbacks` function and essentially build a default `ManagedGroupConfig` already. And we already provide a default `UpdatePolicy`. Providing a default set of callback functions and settings might be a nice feature, if only for testing. Since it's security critical (as it contains settings for padding and the update policy) we should be careful, though.

**Comment by raphaelrobert** [comment]
This has been fixed a while ago.
