### ISSUE TITLE
Handle and test different MLS protocol versions

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#34]
We will start with a pre-RFC version of MLS and need ways to upgrade from one version to another.
MLS protocol versions were introduced in #382.

- [ ] Test with different protocol versions
  - [ ] negative tests
  - [ ] parallel use of different versions
  - [ ] pre-rfc

**Comment by raphaelrobert** [comment]
Reopening because we still have stuff like `ProtocolVersion::Mls10Draft11` and we should get rid of that.

**Comment by franziskuskiefer** [comment]
Then file a new issue for that please. The description here clearly says it's about something else.

**Comment by raphaelrobert** [comment]
Closing in favor of https://github.com/openmls/openmls/issues/1513
