### ISSUE TITLE
[Feature request] Save keys from ManagedGroup in KeyStore

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#345]
**Is your feature request related to a problem? Please describe.**
Keys should only be saved in the ne `KeyStore` whenever possible

**Describe the solution you'd like**
`KeyStore` should provide an appropriate API.

**Describe alternatives you've considered**
Keep the keys in `ManagedGroup`

**Additional context**
None

**Comment by kkohbrok** [comment]
I believe this is a dupe of #337 and can be closed.
