### ISSUE TITLE
[Feature request] Don't clone proposals of the proposal queue

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#347]
**Is your feature request related to a problem? Please describe.**
Proposals are cloned when they are converted into a specific proposal type.

**Describe the solution you'd like**
Not clone.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by franziskuskiefer** [comment]
> Having to collect something here sounds like the APIs are bad. But that's probably nothing to solve in this PR.

_Originally posted by @franziskuskiefer in https://github.com/openmls/openmls/pull/397#r620043832_

**Comment by raphaelrobert** [comment]
This is somewhat outdated after #667. Cloning still happens, and it is also necessary because we keep proposals in both the `StagedCommit` and the original `ProposalQueue`. It is not obvious that we can improve performance here, there's also the risk that the serialization gets altered and we would have to introduce a migration mechanism. Beyond that, it is also unclear whether this constitutes a noteworthy performance bottleneck. However, there seems to be one `.clone()` that we could easily eliminate.
