### ISSUE TITLE
[Feature request] Make OpenMLS more performant

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#358]
**Is your feature request related to a problem? Please describe.**
OpenMLS currently has a few bottlenecks that were non-trivial to solve at the time we discovered them.

**Describe the solution you'd like**
OpenMLS should perform reasonably well for large-ish groups.

**Additional context**
This is a meta feature-request to track bottlenecks in performance we discover during development. That deserve attention independently from the task during which they are discovered. If anyone finds that OpenMLS is slow or shows sub-par performance for some scenarios, this would be a good place to check if this already a known issue.

- [x] #359

**Comment by raphaelrobert** [comment]
I'll close this for now, we can re-open this when we have more concrete ideas.
