### ISSUE TITLE
[Feature request] Avoid cloning of public tree for ratchet tree extension

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#359]
**Is your feature request related to a problem? Please describe.**
If a group has a ratchet tree extension, it has to clone the public tree whenever a commit is created or applied to instantiate the extension. For large groups, this can be quite an expensive operation.

**Describe the solution you'd like**
I have no particular solution, but currently the tree is first cloned, to create the extension and then serialized (for which I believe it has to be cloned again). Maybe it's possible to serialize the tree directly and serialize the rest of the extension around it?

**Comment by raphaelrobert** [comment]
This is now obsolete, because we only generate the ratchet tree extension when we actually need it to invite new members.
