### ISSUE TITLE
Check if path_secret has to be optional in new_from_welcome

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#36]
https://github.com/raphaelrobert/maelstrom/blob/df3d83d45961d47a94fc5a21a8978ee8acc2421c/src/group/mls_group/new_from_welcome.rs#L100-L100

**Comment by franziskuskiefer** [comment]
According to spec this is optional. But does this make sense?

```
struct {
  opaque joiner_secret<1..255>;
  optional<PathSecret> path_secret;
} GroupSecrets;

```

**Comment by kkohbrok** [comment]
The `path_secret` could be `None`, if you were added as part of an `Add-only` commit. If that is the case, the direct paths to the new joiners are blanked (or "tainted"?) and there is no `path_secret` that the new member should know. Thus, the only secret that the new member knows is their `leaf_secret` (or rather their `HPKEPrivateKey`). The next update is then KEMed directly to the corresponding public key.

@raphaelrobert I think you explained to me recently that the direct paths are not necessarily blanked. Can you confirm what I explained above?

**Comment by raphaelrobert** [comment]
Yes, that's correct and intended.
