### ISSUE TITLE
[Bug] Build failure on macOS

### ISSUE THREAD

**Issue by bifurcation** [openmls/openmls#363]
**Describe the bug**
Build fails when building the Evercrypt crate.  Reporting it here because (a) the error is different when building OpenMLS than when building the Evercrypt crate directly, and (b) because @franziskuskiefer is in charge either way.

**To Reproduce**
On macOS 10.14.6, with homebrew-installed gcc `10.2.0_4`.

```
git clone https://github.com/openmls/openmls.git
cd openmls
cargo build # works with or without --verbose --release
```

**Expected behavior**
It builds.

**Actual behavior**
It doesn't build.

**Screenshots or debug log**
https://gist.github.com/bifurcation/7b1df0a7f4447209c8a8b88d161c3dec

**Platform (please complete the following information):**
* macOS 10.14.6
* gcc 10.2.0_4 installed via homebrew (appears that it may not have been used)

**Comment by raphaelrobert** [comment]
Thanks for reporting @bifurcation! It appears to be a problem that recently occurred upstream in `hacl`. This might be related:

https://github.com/project-everest/hacl-star/issues/412
https://github.com/project-everest/hacl-star/issues/407

I filed this in the meantime: https://github.com/franziskuskiefer/evercrypt-rust/issues/20.

**Comment by beurdouche** [comment]
Looks unrelated to those two issues...
