### ISSUE TITLE
Change clippy CI

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#375]
Clippy on CI currently uses `all-features`, which leads to a lot of unused code warnings due to the current interop test setup.
Only enable features here we actually want enabled for clippy.

https://github.com/openmls/openmls/blob/6ef531b38b7a03452c6e78c890f1187ef63abae5/.github/workflows/tests.yml#L46

**Comment by raphaelrobert** [comment]
While clippy still doesn't work, this is no longer a problem.
