### ISSUE TITLE
Optimize cursor to avoid unnecessary encoding of payloads

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#393]
I didn't want to touch the `Cursor` to copy the encoded payload... There will be more versions of this in future that make all this nicer...

_Originally posted by @franziskuskiefer in https://github.com/openmls/openmls/pull/391#discussion_r616698887_

**Comment by kkohbrok** [comment]
Even after switching to the `tls_codec` crate, this is still an issue. The serialized KeyPackage is de-serialized and then serialized again to populate the `encoded` field.

**Comment by raphaelrobert** [comment]
Closing this, since the `KeyPackage` no longer has that field.
