### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#401]
Before a first somewhat stable release the public API has to be well defined.

- [x] clean up the public API
   - [x] #808
   - [x] #809
   - [x] #852 
- [x] #598 
   - [x] #744
- [x] add feature flags for different API levels (also see #215)
- [x] #261 
- [x] describe API usage in book
- [x] #206
- [x] #265
- [x] #438
- [x] #738
- [x] #791

**Comment by raphaelrobert** [comment]
Our work here is done.
