### ISSUE TITLE
Refactor Tree Node and Hash

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#419]
In `refresh_private_tree` we currently have to sign an unfinished key package bundle in order to compute the parent hash. This is because the parent hash computation takes the key package from the node. With splitting unsigned key packages from signed key packages Nodes should be able to hold both. Alternatively the parent hash computation needs to be given the public key of the leaf.

**Comment by kkohbrok** [comment]
The parent hash computation now takes place before the KeyPackage is made into a node, which avoids this issue.
