### ISSUE TITLE
Rely on HPKE where possible (not individual primitives) (#338)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#46]
This might be already the case. If so, feel free to close.

https://github.com/mlswg/mls-protocol/pull/338

**Comment by franziskuskiefer** [comment]
Code review

**Comment by raphaelrobert** [comment]
Rename `ciphersuite.hash_length()`

**Comment by raphaelrobert** [comment]
Closing this, because the hash length we use is the digest size of the ciphersuite in use.
