### ISSUE TITLE
[Feature request] Support importing external `private_key` for `CredentialBundle`

### ISSUE THREAD

**Issue by adzialocha** [openmls/openmls#461]
**Is your feature request related to a problem? Please describe.**

Currently there is no way to pass an external `private_key` during creating of an `CredentialBundle` instance which does not allow for protocols where the private key is also used for features outside of MLS.

**Describe the solution you'd like**

An additional constructor in `CredentialBundle` which allows me to pass on a `private_key` via `SignatureKeypair` as a method argument.

**Additional context**

https://github.com/openmls/openmls/blob/main/openmls/src/credentials/mod.rs#L159

**Comment by kkohbrok** [comment]
Hi @adzialocha,
thanks for the feature request! This is already on our TODO list and will be part of [this project](https://github.com/openmls/openmls/projects/12). In the short term, we could simply create a constructor that allows for this, but our current aim is to tackle this while dealing with the larger question of how to handle persistence for key material.
