### ISSUE TITLE
[MLS Spec change] Fix typo in Parent Hash verification

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#474]
**Description of the changes**
Fix typo in Parent Hash verification 

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/460

**Comment by kkohbrok** [comment]
Dupe of #380?

**Comment by raphaelrobert** [comment]
If you are sure this change has been implemented, you can close.

**Comment by kkohbrok** [comment]
This was indeed fixed. See here specifically: https://github.com/openmls/openmls/pull/390/files#diff-f483c527ae14a7bfefeb3ee2a1e2eefec1cba21c7295f35e374d407dd5f56ea1R240.
