### ISSUE TITLE
[MLS Spec change] Rename add-only Commit to partial Commit

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#475]
**Description of the changes**
Rename add-only Commit to partial Commit.

The important part is that partial Commits can also contain PSK proposals.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/465

**Comment by kkohbrok** [comment]
Dupe of #421?

**Comment by raphaelrobert** [comment]
Looks like it a dupe, but I'm not sure #446 fully addressed the issue. Partial commits can have PSK proposals as well, I think the current code only checks for "add-only" commits. I recommend we leave this open until we have certainty.
