### ISSUE TITLE
[MLS Spec change] Revisit the notion of identity in MLS groups (#476)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#479]
This change is super seeded by https://github.com/mlswg/mls-protocol/pull/509.

**Description of the changes**
A new field `endpoint_id` is added to the KeyPackage. The tuple `(identity, endpoint_id)` now needs to be unique per group.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/476

**Comment by franziskuskiefer** [comment]
super seeded (undone) by https://github.com/mlswg/mls-protocol/pull/573

**Comment by raphaelrobert** [comment]
> super seeded (undone) by [mlswg/mls-protocol#573](https://github.com/mlswg/mls-protocol/pull/573) (#818)

I think this change is indeed completely reverted in #818 and draft-16 does not contain any mention of endpoint IDs anymore.
