### ISSUE TITLE
docs.rs fails to build documentation

### ISSUE THREAD

**Issue by dvc94ch** [openmls/openmls#497]
useful for getting started with openmls

- [0] https://docs.rs/crate/openmls/0.3.0

**Comment by franziskuskiefer** [comment]
This will be fixed with the v0.4 release.

**Comment by franziskuskiefer** [comment]
I'm closing this as the first v0.4 pre-release version builds fine on docs.rs

https://docs.rs/openmls/0.4.0-pre.1/openmls/index.html
