### ISSUE TITLE
KeyPackages should implement the same pattern as `MlsPlaintext`

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#506]
Ultimately KeyPackages should just follow the same pattern as `MlsPlaintext`, thus enforcing verification at type level. But until it does, I think we should leave this in.

_Originally posted by @kkohbrok in https://github.com/openmls/openmls/pull/500#r728921342_

- [x] #459

**Comment by raphaelrobert** [comment]
This was done by #1346.
