### ISSUE TITLE
[Feature request] Include interop tests with MLSpp on CI

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#511]
We currently check our own test vectors as part of the integration tests and there are #490 and #495 tracking the inclusion of MLSpp test vectors as well. However, it would be good to enable live interop testing with MLSpp as well, thus ensuring that we have up-to-date test vectors and allowing for testing of the [szenarios](https://github.com/mlswg/mls-implementations/blob/main/test-scenarios.md) in the future.

**Comment by raphaelrobert** [comment]
Closed via #1370.
