### ISSUE TITLE
Test node hashes (#352)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#52]
https://github.com/mlswg/mls-protocol/pull/352

**Comment by franziskuskiefer** [comment]
This is already the case but let's write a test.

**Comment by raphaelrobert** [comment]
> This is already the case but let's write a test.

Happy to write a test. What would you like to test specifically @franziskuskiefer?

**Comment by franziskuskiefer** [comment]
I guess I meant that we test what this change says, i.e. a correctness check for the `LeafNodeHashInput: node_index`:

> Note that the `node_index` field contains the index of the leaf among the nodes
in the tree, not its index among the leaves; `node_index = 2 * leaf_index`

This might be tested in other ways by now already. If we are certain there's test coverage that this value is correct, we can close this.

**Comment by raphaelrobert** [comment]
We get that through type safety:

```
pub struct LeafNodeHashInput<'a> {
    node_index: &'a NodeIndex,
    key_package: &'a Option<KeyPackage>,
}
```

I don't see any risk of confusion and will close this.
