### ISSUE TITLE
[MLS Spec change] Normalize the description of the zero vector

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#543]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/496

**Comment by franziskuskiefer** [comment]
OpenMLS is doing this already. An empy secret is created as a `Nh`-length vector of zeroes

https://github.com/openmls/openmls/blob/46a3c2b9d98e2f32cab1d14035f754aa3e231f0b/openmls/src/ciphersuite/secret.rs#L76-L78
