### ISSUE TITLE
Adapt to Edition 2021

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#544]
With #521 we switch to Rust Edition 2021. This issue tracks improvements we can do in OpenMLS because of this.

Good to move it to 2021, but did you check everything that could be changed?

_Originally posted by @raphaelrobert in https://github.com/openmls/openmls/pull/521#discussion_r747408585_

**Comment by raphaelrobert** [comment]
I checked https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html and I ran the assisted migration with `cargo fix --edition` and I think there's nothing else to be done for Rust edition 2021.
