### ISSUE TITLE
Implement ExternalInit Proposal

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#556]
https://messaginglayersecurity.rocks/mls-protocol/draft-ietf-mls-protocol.html#section-11.1.6

An ExternalInit proposal is used by new members that want to join a group by using an external commit. This proposal can only be used in that context.

```
struct {
  opaque kem_output<0..2^16-1>;
} ExternalInit;
```

A member of the group applies an ExternalInit message by initializing the next epoch using an init secret computed as described in Section 8.1. The `kem_output` field contains the required KEM output.

**Comment by kkohbrok** [comment]
I already made some progress (#488), but stopped to wait for the validation work. I could take up the work again now, but at this point, it might be worth waiting for the tree rewrite.
