### ISSUE TITLE
Fix clippy on CI

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#561]
Clippy does not seem to highlight any warnings in PRs anymore.

**Comment by duesee** [comment]
* [ ] Check https://github.com/openmls/openmls/pull/1171#discussion_r1060535307

**Comment by duesee** [comment]
Are we happy with Clippy as is? See, e.g., https://github.com/openmls/openmls/actions/runs/3835992919/jobs/6529706947?

Raphael [suggested to use](https://github.com/openmls/openmls/pull/1171#discussion_r1060520230) `--message-format=json` but I'm not sure if this is an improvement. I guess that people are used to look at failed steps and might not recognize GitHub's parsed JSON output at the bottom? So when we bring this in place they will only see an unreadable JSON in the step?

**Comment by franziskuskiefer** [comment]
Lets consider this done for now.
