### ISSUE TITLE
[Feature request] Decrypt application messages from past epochs

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#563]
Currently, the key material is discarded during each epoch change. This means that application messages can no longer be decrypted if they belong to a past epoch. It would be good to keep older key material around (while being mindful of general FS implications) according to configurable parameters. Parameters could be a maximum number of epochs and a maximum time (whichever comes first).

**Comment by adzialocha** [comment]
This is really interesting, we originally thought about a very similar logic like this on top of MLS :+1:

**Comment by raphaelrobert** [comment]
Currently blocked by #423.
