### ISSUE TITLE
Validate GroupContextExtensions Proposal

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#566]

**Comment by kkohbrok** [comment]
Re-opening this at least as long as we don't add GCE proposals into the `valid_proposals` pool in `filter_proposals`. As long as they're not in the pool, they are not included in commits and can't properly be validated. Once that happens, we can include GCE proposals into validation tests, for example when testing for path presence [here](https://github.com/openmls/openmls/pull/1108#discussion_r1031569123).

**Comment by franziskuskiefer** [comment]
This should've been closed by #1475
