### ISSUE TITLE
[Bug] CLI is broken on main branch

### ISSUE THREAD

**Issue by pulkitkothari** [openmls/openmls#593]
**Describe the bug**
The CLI tool is broken on main branch.

**To Reproduce**
cargo run

**Expected behavior**
No exception

**Actual behavior**
Build error

**Screenshots or debug log**
➜  cli git:(main) ✗ cargo run
   Compiling openmls v0.3.0 (\~/openmls/openmls)
   Compiling rust_crypto v0.1.0 (~/openmls/rust_crypto)
error[E0599]: no function or associated item named `from_bytes` found for struct `ed25519_dalek::Signature` in the current scope
   --> ~/openmls/rust_crypto/src/lib.rs:258:48
    |
258 |                     &ed25519_dalek::Signature::from_bytes(&sig)
    |                                                ^^^^^^^^^^ function or associated item not found in `ed25519_dalek::Signature`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use ed25519_dalek::ed25519::signature::Signature;
    |
help: there is an associated function with a similar name
    |
258 |                     &ed25519_dalek::Signature::to_bytes(&sig)
    |                                                ~~~~~~~~

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rust_crypto` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

**Platform (please complete the following information):**
macOS

**Comment by raphaelrobert** [comment]
Building it should work (according to the CI). Did you try to do a `cargo update`?

Note that we don't do much testing for the CLI tool, so other things might still not work.

**Comment by pulkitkothari** [comment]
Oh yes I missed to do cargo update. I will also soon move away from using cli. Thanks
