### ISSUE TITLE
Compatibility with pre-release versions

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#641]
We currently treat ciphersuites and MLS versions separate. In theory, that allows us to treat different pre-release versions separate from one-another, but we're not really using it in any way. We shoul decide to which degree we want to support pre-release versions, how that separation is implemented and how we use it in tests.

**Comment by kkohbrok** [comment]
I filed https://github.com/mlswg/mls-protocol/pull/532, the result of which might yield a way to treat the problem that works across implementations.

**Comment by raphaelrobert** [comment]
Duplicate of #628.
