### ISSUE TITLE
"Supported ciphersuite" is unclear

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#701]
This came up in the course of #699.

There are two functions `supported_ciphersuites`, which accesses the `Config` and `supported_ciphersuite_names`, which accesses a constant that is independent of the config. `supported_ciphersuite_names` should probably refer to `supported_ciphersuites` for its output.

**Comment by franziskuskiefer** [comment]
The crypto provider trait should get functions for checking algorithm support. This should then be piped through unless the config explicitly disables cipher suites.
