### ISSUE TITLE
[MLS Spec change]  Require extensions to be unique in any given extensions vector (#535)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#720]
**Description of the changes**
See title.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/535

**Comment by duesee** [comment]
The change is ...

> * Any field containing a list of extensions MUST NOT have more than one extension of any given type.

I would like to tackle this by introducing a Wrapper around `Vec` that ensures uniqueness and fixup all compilation problems afterwards.

**Comment by duesee** [comment]
Before tackling this, we should introduce a `KeyPackageBundleBuilder`. This way, we can cleanup the API and avoid to touch all tests again when solving this issue here.
