### ISSUE TITLE
[MLS Spec change] Reword padding section to reflect updated padding structure (#536)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#721]
**Description of the changes**
No concrete changes, I believe, but we should double-check.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/536

**Comment by franziskuskiefer** [comment]
@duesee after touching #913, please have a look what we need to do here.

**Comment by duesee** [comment]
Nothing to do here. The mlswg PR is now outdated and OpenMLS implements draft-16.
