### ISSUE TITLE
[Bug] Unable to get Group epoch 

### ISSUE THREAD

**Issue by pulkitkothari** [openmls/openmls#723]
**Describe the bug**
The group has group context which is not public, so application code is unable to get epoch from a MlsGroup.

**To Reproduce**
No method get epoch for a MlsGroup

**Expected behavior**
MlsGroup should have a method to get epoch

**Actual behavior**
No method

**Proposed fix:**
https://github.com/openmls/openmls/blob/main/openmls/src/group/mls_group/mod.rs#L180
```
MlsGroup {
...
    /// Return the epoch
    pub fn epoch(&self) -> GroupEpoch {
        return self.group.context().epoch();
    }

...
}
```

**Comment by raphaelrobert** [comment]
This looks like a reasonable thing to expose indeed.
