### ISSUE TITLE
[MLS Spec change]  Be consistent about version labeling (#543)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#733]
**Description of the changes**
Usage of the MLS version as label is made consistent across the spec.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/543

**Comment by duesee** [comment]
The only change done in the mls-protocol PR is ...

```diff
struct {
    uint16 length = Length;
-    opaque label<7..255> = "mls10 " + Label;
+    opaque label<7..255> = "MLS 1.0 " + Label;
    opaque context<0..2^32-1> = Context;
} KDFLabel;
```

I can find [one instance](https://github.com/openmls/openmls/blob/main/openmls/src/versions.rs#L71) of `"mls10"` in the OpenMLS code and would just change it to `"MLS 1.0"`.

From my understanding, [`KDFLabel::serialized_label`](https://github.com/openmls/openmls/blob/5126797d45c1c46617489be6c2aeb1912bdfeeaf/openmls/src/ciphersuite/kdf_label.rs#L16) could already write out `b"MLS 1.0 "`. But it seems this is already taken care of [elsewhere](https://github.com/openmls/openmls/blob/71684016ee50a17e285d3429e443456a0af4bdcd/openmls/src/ciphersuite/secret.rs#L173).

Is there anything more to be done here that I might miss?
