### ISSUE TITLE
[MLS Spec change]  Domain separation for KeyPackage and Proposal references (#547)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#735]
**Description of the changes**
Hashreferences for Proposals and KeyPackages are now generated with a string as label indicating if it's a key package or a proposal reference.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/547

**Comment by franziskuskiefer** [comment]
@nomaxg is working on this

**Comment by nomaxg** [comment]
👍
