### ISSUE TITLE
Re-enable group tests

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#77]
Currently the group tests are disabled and should be re-enabled when the API changes are complete.

**Comment by franziskuskiefer** [comment]
The tests probably have be re-written.

https://github.com/raphaelrobert/maelstrom/blob/06f5130042906b069f9ad5d06e853fc30490d587/tests/test_group.rs#L187

**Comment by franziskuskiefer** [comment]
Looking at the code all tests in `test_group.rs` should currently fail because they use invalid key packages. But they don't.
