### ISSUE TITLE
[MLS Spec change]  Rename InitKeys -> KeyPackages; and GroupInfo -> PublicGroupState (#551)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#815]
**Description of the changes**
Renaming of structs.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/551

**Comment by duesee** [comment]
* [ ] Rename `InitKeys` to `KeyPackages`.
* [ ] Rename `GroupInfo` to `PublicGroupState`.
  In draft-ietf-mls-protocol-16 it is still called `GroupInfo`. Second PR?

**Comment by franziskuskiefer** [comment]
I agree there's nothing further to do in this issue.
