### ISSUE TITLE
[MLS Spec change]  Exempt default features from RequiredCapabilities (#560)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#816]
**Description of the changes**
Proposals and Extensions from the spec are required by default (i.e. MTI).

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/560

**Comment by franziskuskiefer** [comment]
This depends on moving the required capabilities to the leaf node in #819.

**Comment by franziskuskiefer** [comment]
I think this is implemented, but should be double checked before closing.

**Comment by duesee** [comment]
See, e.g., https://github.com/openmls/openmls/blob/6bb082b01195b29417483cae5abb34c0d7f58303/openmls/src/treesync/node/leaf_node.rs#L795
