### ISSUE TITLE
[MLS Spec change] Forbid proposals by reference in external commits (#562)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#817]
**Description of the changes**
As the title says.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/562

**Comment by beltram** [comment]
I'd like to be assigned this issue

**Comment by duesee** [comment]
Hm... I can't assign @augustocdias :-) I guess need to comment here first?

**Comment by augustocdias** [comment]
Please assign me this issue.

**Comment by franziskuskiefer** [comment]
To ensure this on the radar for this issue.

So, basically, what I think we should do is to remove the "inline" from all ValSems covering external commits and remark that "inline" is implied by "external commit". 

_Originally posted by @duesee in https://github.com/openmls/openmls/issues/986#issuecomment-1330517758_

There is a working test for ValSem242 that covers inline Add proposals (but not referenced Add proposals.) Thus, I think we can close this issue or link to https://github.com/openmls/openmls/issues/817.

_Originally posted by @duesee in https://github.com/openmls/openmls/issues/986#issuecomment-1330532664_
