### ISSUE TITLE
[MLS Spec change] Split LeafNode from KeyPackage (#575)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#819]
**Description of the changes**
As the title says. Result are two distinct structs for pre-publishing key material and populating leaf nodes in trees.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/575

- [x] #894
- [x] #818 
- [ ] #893
- [x] #968
- [x] #1088

**Tracking required changes**
- [x] Unambiguous signatures (#980)

**Open items**
- [ ] High level API design
- [x] ~~Re-introduce caching of tree hashes~~
- [ ] Avoiding excessive cloning of leaf nodes
- [x] #1140
- [x] Ensure sign/verify flows for leaf nodes is clean and safe
- [x] #727
- [x] #885
- [x] Cleanup extensions
- [x] Cleanup setting of lifetimes for leaf nodes.
- [x] #1226

**Comment by franziskuskiefer** [comment]
I'm closing this now that most of the work is done.
#893 is one open follow up spec change and there are a few things like API design we want to do, but that's either tracked separately or not a spec change.
