### ISSUE TITLE
[MLS Spec change] Enforce uniqueness of PreSharedKeyIDs in PreSharedKey proposals (#579)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#820]
**Description of the changes**
As the title says.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/579

**Comment by augustocdias** [comment]
Can you assign me this issue please?

**Comment by augustocdias** [comment]
So it seems the change referred in the ticket was undone by this [commit](https://github.com/mlswg/mls-protocol/commit/a662e60c3584eb3d7d5a94694ca719b515d88114). Should I do it anyways?

**Comment by duesee** [comment]
@raphaelrobert, could you help here?

**Comment by raphaelrobert** [comment]
It looks like this has moved indeed. There's nothing to do about this issue.
