### ISSUE TITLE
[Bug] When chosing to input a KeyPackage, `self_update` creates an Update proposal

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#821]
The `self_update` function of the `mls_group` API takes an optional `KeyPackage` as input. When that happens, the function creates an update proposal from that KeyPackage and tries to commit it. However, committing update proposals with one's own KeyPackages is not allowed and the `path` must be used instead.

For the function to change this behaviour, the `CreateCommitParams` struct needs to allow the caller to pass in an explicit KeyPackage, which can then be used as basis for the `path`. Also, a test should be added that actually does this.

**Comment by raphaelrobert** [comment]
`self_update` no longer takes a `KeyPackage` (or a `LeafNode` for that matter), therefore this is no longer an issue. In fact, #1208 is proposing to reintroduce this.
