### ISSUE TITLE
[Bug] Wrong label when computing `KeyPackageRef`

### ISSUE THREAD

**Issue by pcapriotti** [openmls/openmls#872]
The key package calculation in `KeyPackage::hash_ref` is using the wrong label: [here](https://github.com/openmls/openmls/blob/main/openmls/src/ciphersuite/hash_ref.rs#L30) the label is hardcoded to "MLS 1.0 ref", while the spec mandates "MLS 1.0 KeyPackage Reference". Presumably this is a problem for proposals as well.

**Comment by raphaelrobert** [comment]
That is part of https://github.com/openmls/openmls/issues/735 I think.

**Comment by franziskuskiefer** [comment]
#735 has been closed
