### ISSUE TITLE
[MLS Spec change] Clean up the description of tree evolution. (#593)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#876]
**Description of the changes**
This PR notes that it's possible to generate the leaf keypairs independently from the rest of the path. We could implement this to save a few derivation operations, but the current solution of deriving the whole path at once is probably easier.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/593

**Comment by franziskuskiefer** [comment]
Thanks for tackling this @nomaxg. I assigned you the issue.

**Comment by franziskuskiefer** [comment]
Has this been fully addressed with #1139, i.e. can we close this, or is there another PR coming up? @kkohbrok can you check as well please as you reviewed #1139.

**Comment by kkohbrok** [comment]
This has indeed been addressed with #1139. Closing.
