### ISSUE TITLE
[MLS Spec change] Require Commit.path by default (#597)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#879]
**Description of the changes**
This PR changes the way that the spec indicates if a path is required or not. There has been no change in terms of semantics, I think, but we might want to make sure that we're implementing it the way it's described in the spec.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/597

**Comment by beltram** [comment]
I'd like to be assigned this issue

**Comment by franziskuskiefer** [comment]
@duesee was the self-assign on purpose or did you want to assign to @beltram?

**Comment by duesee** [comment]
Ah, sorry. I wanted to assign it to @beltram.
