### ISSUE TITLE
[MLS Spec change] Better name for preconfigured sender ID (#598)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#880]
**Description of the changes**
Changes the name of the preconfigured sender ID.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/598

**Comment by duesee** [comment]
The only required change for this would be to rename a field `external_key_id` to `sender_id`. However, the translation of ...

```tls
struct {
    SenderType sender_type;
    switch (sender_type) {
        case member:        LeafNodeRef member;
        case preconfigured: opaque external_key_id<V>;
        case preconfigured: opaque sender_id<V>;
        case new_member:    struct{};
    }
} Sender;
```

... to ...

```rust
#[repr(u8)]
pub enum Sender {
    /// The sender is a member of the group
    #[tls_codec(discriminant = 1)]
    Member(KeyPackageRef),
    /// The sender is not a member of the group and has a preconfigured value instead
    Preconfigured(TlsByteVecU8),
    /// The sender is a new member of the group that joins through an External Commit
    NewMember,
}
```

(https://github.com/openmls/openmls/blob/main/openmls/src/framing/sender.rs#L11-L20)


... drops the field name entirely. If I am not mistaken, there is nothing to do here.

**Comment by duesee** [comment]
Yay, first issue in OpenMLS closed by doing... nothing! 🥳
