### ISSUE TITLE
[MLS Spec change] Add version to MLSMessage (#600)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#881]
**Description of the changes**
As the title says.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/600

**Comment by duesee** [comment]
### Changes

* Add `version` to `MLSMessage` https://github.com/mlswg/mls-protocol/pull/600/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f79c994d22a604aR1380
* Add `version` to `MLSMessageContentTBS` https://github.com/mlswg/mls-protocol/pull/600/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f79c994d22a604aR1445
* Remove `version` from `GroupInfo` https://github.com/mlswg/mls-protocol/pull/600/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f79c994d22a604aL3648
* Add verification of version number https://github.com/mlswg/mls-protocol/pull/600/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f79c994d22a604aR2795

**Comment by duesee** [comment]
@franziskuskiefer :-)

**Comment by franziskuskiefer** [comment]
Blocked on [#979](https://github.com/openmls/openmls/issues/979)
