### ISSUE TITLE
[MLS Spec change] Limit the new variable length encoding to 30-bit (#602)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#882]
**Description of the changes**
This is probably only relevant to TLS-codec, but we should make sure we're honoring this limit.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/602

**Comment by franziskuskiefer** [comment]
Tracked in #877

**Comment by franziskuskiefer** [comment]
This was fixed in https://github.com/RustCrypto/formats/pull/751.
