### ISSUE TITLE
[MLS Spec change] Preconfigured senders extension and removal of signature key indirection (#617)

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#884]
**Description of the changes**
Removes the indirection of signature keys for message verification and introduces a preconfigured senders extension.

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/617

---

* [x] #1087
* [x] #1088
* [x] #1112

**Comment by duesee** [comment]
* [ ] Preconfigured senders extension (#884_1)
* [ ] and removal of signature key indirection (#884_2)
