### ISSUE TITLE
Proposed flow for creating a `CredentialBundle` from external key-pair

### ISSUE THREAD

**Issue by adzialocha** [openmls/openmls#898]
For our specific use-case we need to create `CredentialBundle` from an external key pair. Based on the [documentation](https://github.com/openmls/openmls/blob/f3498e6e3dea03202c52da2c4eb9bf676b3075ab/book/src/user_manual/crypto-subtle.md) I expect to do this via the `SignatureKeypair::from_bytes` method which can then be used for `CredentialBundle::from_parts`. I've activated the `crypto-subtle` feature but it seems to still not be possible:

1. `openmls::prelude::SignatureKeypair` is not public
  ```
error[E0603]: struct `SignatureKeypair` is private
 --> src/secret_group/mls/member.rs:4:23
  |
4 | use openmls::prelude::SignatureKeypair;
  |                       ^^^^^^^^^^^^^^^^ private struct
```

2. `CredentialBundle::from_parts` can only be used for testing / is not public
  ```
error[E0599]: no function or associated item named `from_parts` found for struct `CredentialBundle` in the current scope
  --> src/secret_group/mls/member.rs:48:48
   |
48 |                 let bundle = CredentialBundle::from_parts(public_key.to_vec(), signature_key_pair);
   |                                                ^^^^^^^^^^ function or associated item not found in `CredentialBundle`
  ```

What is the proposed flow to achieve this? Probably I'm missing something? Thank you!

**Comment by franziskuskiefer** [comment]
Yep, this was fixed in #873. @raphaelrobert it would be nice if we'd add the PRs to the CHANGELOG.md then the changes are easier to find 🙂

**Comment by adzialocha** [comment]
Thank you!! :slightly_smiling_face: Is there an ETA for a release which will contain this release? We would like to publish our crate and `openmls` is our last (unreleased) dependency.

**Comment by raphaelrobert** [comment]
I'll look into it
