### ISSUE TITLE
Enforce FS for secret tree

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#91]
Make sure `encryption_secret` is deleted as soon as the secret tree is created.

**Comment by kkohbrok** [comment]
I think it would be a good idea to use `secrets::Secret` for keys/secrets then?
For reference: https://docs.rs/secrets/0.11.1/secrets/struct.Secret.html

**Comment by franziskuskiefer** [comment]
Not sure if that crate is really what we need. Looks like this is doing a lot we don't need.
