### ISSUE TITLE
[MLS Spec change] Make padding arbitrary-size and all-zero (#650)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#913]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/650

**Description of the changes**
> Fixes #642 
 > 
 > Also requires that padding be all-zero.  Before, the sender was allowed to put arbitrary octets in there.

**Comment by duesee** [comment]
Okay, so we have two changes here ...

```diff
struct {
    select (MLSCiphertext.content_type) {
        case application:
          opaque application_data<V>;
        case proposal:
          Proposal proposal;
        case commit:
          Commit commit;
    }

    MLSMessageAuth auth;
-   opaque padding<V>;
+   opaque padding[length_of_padding];
} MLSCiphertextContent;
```

... and the added requirement that the padding is all-zero ...

> The `padding` field MUST be filled with all zero bytes.  A receiver MUST verify that
there are no non-zero bytes in the `padding` field, and if this check fails, the
enclosing MLSCiphertext MUST be rejected as malformed.

**Comment by duesee** [comment]
First question: Where dies `length_of_padding` come from?

**Comment by duesee** [comment]
Good: zero-bytes. TODO: Do not encode as `TlsByteSliceU16` but append "raw" (https://github.com/openmls/openmls/blob/main/openmls/src/framing/ciphertext.rs#L356)

**Comment by duesee** [comment]
I've opened a draft PR #1074. Can you have a look if this looks sane? Specifically, how does this `ValSem` thing works exactly?

**Comment by duesee** [comment]
After thinking a bit about it I'm leaning towards thinking that this was a good spec change. Making the length implicit forces us to consume the decrypted bytes. Otherwise it could happen that someone encodes trailing data. Not sure about the consequences but doesnt seem great.
