### ISSUE TITLE
[MLS Spec change] Miscellaneous changes (#656)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#917]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/656

**Description of the changes**
>

**Comment by raphaelrobert** [comment]
Not strictly editorial despite the name.

**Comment by franziskuskiefer** [comment]
The only technical change in here is to make the variable-length TLS encoding is safe. This will be tackled as part of #882.
