### ISSUE TITLE
[MLS Spec change] Replace LeafNodeRef with leaf index. (#658)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#918]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/658

**Description of the changes**
> This seems to be a layer of indirection that doesn't add any value to implementation.

**Comment by franziskuskiefer** [comment]
This undoes the changes from other changes we don't have yet.
There's nothing to do here. This will this be closed with #984.
