### ISSUE TITLE
[MLS Spec change] Remove new_member Add proposals. (#659)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#919]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/659

**Description of the changes**
> Sending an Add proposal from outside the group is how we let people do "external add" functionality without needing to publish the group state. But you can't talk right away like you can with an external Commit. In that case, applications seem more inclined to build this functionality themselves so let's just remove it from the spec.

**Comment by augustocdias** [comment]
From my understanding this change was overlapped by this change: https://github.com/mlswg/mls-protocol/pull/716

In this one it is suggested to remove the `Proposal` `SenderType` and in the linked issue it is suggested to put it back. OpenMls had the implementation for the later one added here: https://github.com/openmls/openmls/pull/902
The referred `SenderTypes` can be seen here:
https://github.com/openmls/openmls/blob/main/openmls/src/framing/sender.rs#L47-L50

This was pointed out to me by @franziskuskiefer and if this assumption is correct there's nothing more to be done here.

**Comment by kkohbrok** [comment]
Thanks for investigating @augustocdias! I believe you are correct. Closing.
