### ISSUE TITLE
Automated code coverage triggered by PRs

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#92]

**Comment by franziskuskiefer** [comment]
This is a good starting point: https://github.com/actions-rs/grcov

**Comment by franziskuskiefer** [comment]
This is pretty much copy&paste from something like this https://github.com/franziskuskiefer/hpke-rs/blob/master/.github/workflows/coverage.yml

**Comment by kkohbrok** [comment]
We got coverage testing via codecov.io now!
