### ISSUE TITLE
[MLS Spec change] Recommend that group ids are generated randomly. (#686)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#926]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/686

**Description of the changes**
> Closes #661

**Comment by franziskuskiefer** [comment]
Ensure that the default ways of generating a `GroupId` is random.

**Comment by duesee** [comment]
Tasks:

* Group IDs SHOULD be constructed in such a way that there's an overwhelmingly low
probability of honest group creators generating the same group ID, even without
assistance from the Delivery Service. For example, by making the group ID a
freshly generated random value of size `KDF.Nh`. -> Change OpenMLS API to use `GroupId::random()` by default.

* ~New members MUST verify that `group_id` is unique among the groups they're
currently participating in.~ --> Can't be done in OpenMLS?

* ~The Delivery Service MAY attempt to ensure that group IDs are globally unique by rejecting the creation
of new groups with a previously used ID.~ -> Delivery Service
