### ISSUE TITLE
[MLS Spec change] Reorganize discussion of ratchet tree concepts (#689)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#929]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/689

**Description of the changes**
> Closes #670 
 > Closes #644 
 > Closes #669 
 > 
 > This PR reorganizes the exposition of tree concept to make them read more clearly.
 > 
 > * A new Paths through the Ratchet Tree section is introduced, which covers direct paths, copaths, and filtered direct paths
 > * The Ratchet Tree Nodes section is moved forward, so that the definition of filtered direct paths can refer to the notion of resolutions (see Bren2010's note on #670)
 > * The path example expanded so that there are blanks in the tree, and so that it shows all three path types (direct, copath, and filtered direct) for every leaf.
 > * The section on verifying parent hashes uses the example tree from the path section to illustrate the concepts noted in #669

**Comment by duesee** [comment]
I don't think we can meaningfully extract some action item from this for OpenMLS and vote to close this issue as being editorial.

**Comment by franziskuskiefer** [comment]
I agree, I don't see any changes here. Please close when you had another look.
