### ISSUE TITLE
[MLS Spec change] Better documentation for transcript hash (#695)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#933]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/695

**Description of the changes**
> Fixes #643 
 > 
 > Changes `MLSMessageCommitContent -> ConfirmedTranscriptHashInput` and `MLSMessageAuthData -> InterimTranscriptHashInput`.

**Comment by duesee** [comment]
Argh... this PR dropped a piece of text that was helpful: "As shown above, when a new group is created, the `interim_transcript_hash` field is set to the zero-length octet string."

Anyway... It renames `MLSMessageCommitContent` to `ConfirmedTranscriptHashInput` and `MLSMessageCommitAuthData` to `InterimTranscriptHashInput`. Besides than that, it is editorial.

Thus, @kkohbrok fixed this yesterday already 🎉 #1111

**Comment by franziskuskiefer** [comment]
@kkohbrok can you confirm that this is fixed?

**Comment by kkohbrok** [comment]
Confirmed!
