### ISSUE TITLE
Clarify some parts of Application Messages section

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#935]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/699

**Description of the changes**
> Closes #679

**Comment by franziskuskiefer** [comment]
There are some useful security considerations in there but no spec changes.

**Comment by raphaelrobert** [comment]
> There are some useful security considerations in there but no spec changes.

No spec changes indeed, closing.
