### ISSUE TITLE
[MLS Spec change] Clarify rules around Add proposals. (#705)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#940]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/705

**Description of the changes**
> Closes #700

**Comment by augustocdias** [comment]
Can you assign this to me?

**Comment by augustocdias** [comment]
Sorry for the long time to implement this. I was sick in the previous weeks and couldn't focus on it.
