### ISSUE TITLE
[MLS Spec change] Clean up struct names and references to them (#706)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#941]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/706

**Description of the changes**
> Closes #673 
 > Closes #674 
 > 
 > With regard to #674: I searched for references to MLSPlaintext and Credential that were obsolete in light of the change to the MLSMessage framework.  (In particular, we used to have the idea that you would encode things as MLSPlaintext, then tranform them to MLSCiphertext if needed; now you encode to AuthenticatedContent and then convert that to MLSPlaintext/MLSCiphertext before sending.)  There were a few fixes for MLSPlaintext; I didn't find anything that needed fixing for Credentia, largely thanks to some PRs that have landed since I did the review that resulted in #674.

**Comment by duesee** [comment]
Changes:

### Renames

* `MLSMessageAuth` --> `MLSContentAuthData`
* `MLSMessageContent` --> `MLSContent`
* `MLSMessageContentAuth` --> `MLSAuthenticatedContent`
* `MLSMessageContentTBS` --> `MLSContentTBS`
* `MLSMessageContentTBM` --> `MLSContentTBM`

* `MLSPlaintext` --> `MLSAuthenticatedContent` (This is confusing?)

### Changes to structs

* Change `GroupInfo` https://github.com/mlswg/mls-protocol/pull/706/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f79c994d22a604aL3930
* Change `GroupInfoTBS` https://github.com/mlswg/mls-protocol/pull/706/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f79c994d22a604aL3952

### Unclear implications (to me)
* https://github.com/mlswg/mls-protocol/pull/706/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f79c994d22a604aL3785
* https://github.com/mlswg/mls-protocol/pull/706/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f79c994d22a604aL3831


### TODO

* https://github.com/mlswg/mls-protocol/pull/706/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f79c994d22a604aL4142
* https://github.com/mlswg/mls-protocol/pull/706/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f* https://github.com/mlswg/mls-protocol/pull/706/files#diff-7c369b85b26a746a7e70cd2884037896defe03b3098bec976f79c994d22a604aL489279c994d22a604aL4457

**Comment by franziskuskiefer** [comment]
Blocked on #979
