### ISSUE TITLE
[MLS Spec change] Derive the commit secret from the end of the UpdatePath, not the root (#707)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#942]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/707

**Description of the changes**
> Fixes #690

**Comment by duesee** [comment]
Issue (Old):
> Define `commit_secret` as the value `path_secret[n+1]` derived from the `path_secret[n]` value assigned to the root node.

Issue (New):
> Define `commit_secret` as the value `path_secret[n+1]` derived from the last path secret value (`path_secret[n]`) derived for the UpdatePath.
    
draft-17:
> Define `commit_secret` as the value `path_secret[n+1]` derived from the last path secret value (`path_secret[n]`) derived for the UpdatePath.

---

In other words ...

```
Derive `path_secret[n+1]` (`commit_secret`) from the `path_secret[n]` value assigned to the root node.

                                            from the last path secret value (`path_secret[n]`) derived for the UpdatePath.
```

**Comment by duesee** [comment]
Deassigning me for the time being as we probably found another thing that needs attention first.
