### ISSUE TITLE
[MLS Spec change] Clarify description of UpdatePath generation and processing (#712)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#945]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/712

**Description of the changes**
> Fixes #671 
 > 
 > Conflicts with #707 (in derivation of `commit_secret`)
 > 
 > This is intended just to move around the required steps and give them clearer labels.  Please keep an eye out for things that might have accidentally been added or dropped.

**Comment by duesee** [comment]
This seems to be an editorial change? @kkohbrok?

**Comment by kkohbrok** [comment]
Seems like I have verified this already by reviewing the original PR on the spec 😁. I trust old me, so I'm closing this.
