### ISSUE TITLE
[MLS Spec change] Improve parent hash guarantees (#713)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#946]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/713

**Description of the changes**
> # A nice security property for parent-hash
 > 
 > The goal of #527 was to have a property similar to:
 > 
 > > If there is a parent-hash chain from the leaf L to a node N, then the signature of L binds the tree Canonicalize(N)
 > 
 > (where Canonicalize(N) is N with its unmerged leaves removed, i.e. the subtree of N the last time a Commit went through it)
 > 
 > However, this is currently not true, there are a few places where we can do (hopefully benign) modifications on N.
 > 
 > Example 1:
 > ```
 >               W
 >         ______|_____
 >        /             \
 >       _               Y
 >     __|__           __|__
 >    /     \         /     \
 >   T       _       X       Z
 >  / \     / \     / \     / \
 > A   B   _   _   E   F   G   H
 > ```
 > 
 > with the parent-hash chain A-T-W (happening with filtered update path).
 > 
 > We can modify the blank subtree:
 > 
 > ```
 >               W
 >         ______|_____
 >        /             \
 >       _               Y
 >     __|__           __|__
 >    /     \         /     \
 >   T       V       X       Z
 >  / \     / \     / \     / \
 > A   B   C   D   E   F   G   H
 > ```
 > 
 > and the parent-hash chain A-T-W is still valid
 > 
 > Example 2:
 > 
 > ```
 >               W
 >         ______|_____
 >        /             \
 >       U               Y
 >     __|__           __|__
 >    /     \         /     \
 >   T       V       X       Z
 >  / \     / \     / \     / \
 > A   B   _   D   E   F   G   H
 > ```
 > 
 > with the parent-hash chain A-T-U-W.
 > 
 > We can add unmerged leaves:
 > 
 > ```
 >               W
 >         ______|_____
 >        /             \
 >       U[C]            Y
 >     __|__           __|__
 >    /     \         /     \
 >   T       V[C]    X       Z
 >  / \     / \     / \     / \
 > A   B   C   D   E   F   G   H
 > ```
 > 
 > and the parent-hash chain A-T-U-W is still valid.
 > 
 > # How to get this property
 > 
 > These examples are not possible if we require the parent-hash check to verify other invariants that exists in MLS:
 > - if there is a parent-hash link from U to P and there are blank nodes between U and P, these blank nodes are here because of the filtered update path so their sibling have empty resolution (this invariant forbids example 1)
 > - if there is a parent-hash link from U to P, then there can't be a leaf which is merged for U but not for P, because U and P were last modified by a commit at the same time (this invariant forbids example 2)
 > 
 > This PR add these checks to the parent hash validation procedure.
 > 
 > # Proof that we do have the property with this PR
 > 
 > ## Definitions
 > 
 > Un-adding leaves:
 > Let N be a node, and Ls a list of leaves.
 > Then UnAdd(N, Ls) is a tree identical to N, except that the leaves of Ls are blanked and removed from every node's unmerged leaves list.
 > Informally, this operation is the inverse of adding leaves Ls in N by participant not in N.
 > 
 > Canonicalization:
 > We define Canonicalize(N) = UnAdd(N, N.unmerged_leaves).
 > 
 > Tree equivalence:
 > We say T1 ~= T2 when Canonicalize(T1) = Canonicalize(T2).
 > 
 > Parent-hash link:
 > We say C ~> P when "the parent hash in a node C is valid with respect to a parent node P" as described in the "Verifying Parent Hashes" section (modified by this PR)
 > 
 > # Key property on ~= and ~>
 > 
 > We prove the following property:
 > If C ~> P
 > and C' ~> P'
 > and C ~= C'
 > then P ~= P'.
 > 
 > This is better understood with a nice square:
 > ```
 > If we have:
 > 
 > C ~= C'
 > ~    ~
 > V    V
 > P    P'
 > 
 > Then there is a ~= between P and P'
 > ```
 > 
 > Proof of this property:
 > 
 > Let S (resp. S') be the sibling in the C ~> P (resp. C' ~> P') relation. Because leaf indices are inside the tree hash, S and S' are both on the same side of P and P'.
 > 
 > Fact 1: UnAdd(S, P.unmerged_leaves) = UnAdd(S', P'.unmerged_leaves).
 > Proof: By definition of the parent hash and injectivity of tree-hash.
 > 
 > Fact 2: UnAdd(C, P.unmerged_leaves) = UnAdd(C', P'.unmerged_leaves).
 > Proof:
 > 
 > ```
 >   UnAdd(C, P.unmerged_leaves)
 > = UnAdd(C, Intersection(P.unmerged_leaves, Leaves(C))     by a simple lemma on UnAdd
 > = UnAdd(C, C.unmerged_leaves)                             by C ~> P (we use the second new invariant here!)
 > = UnAdd(C', C'.unmerged_leaves)                           by C ~= C'
 > = UnAdd(C', Intersection(P'.unmerged_leaves, Leaves(C'))) by C' ~> P' (we use the second new invariant here!)
 > = UnAdd(C', P'.unmerged_leaves)                           by a simple lemma on UnAdd
 > ```
 > 
 > With Fact 1 and Fact 2, we deduce that P ~= P' (we use the first new invariant here!).
 > 
 > # Proof of signature binding
 > 
 > A leaf signature binds the existence of nodes Mi suh that L ~> M1 ~> ... ~> Mm = root
 > 
 > When there is a parent-hash-link path to a node P starting from a leaf L like L ~> N1 ~> ... ~> Nn ~> P, by applying inductively the property on ~= and ~> you get P ~= Mi for some i, hence L's signature binds Canonicalize(P) = Canonicalize(Mi).
 >

**Comment by franziskuskiefer** [comment]
@raphaelrobert can we close this?

**Comment by raphaelrobert** [comment]
Indeed.
