### ISSUE TITLE
[MLS Spec change] Add new new_proposal_member SenderType (#716)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#949]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/716

**Description of the changes**
> Add new new_proposal_member SenderType and rename new_member to new_commit_member. 
 > 
 > This restores the External Proposal Add functionality which was present in the protocol for some years but clarifies how the authorization and signing takes place in this case.
 >

**Comment by franziskuskiefer** [comment]
@beltram is working on this
