### ISSUE TITLE
[MLS Spec change] Include ciphersuite in group context (#720)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#952]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/720

**Description of the changes**
> This will guarantee that all group members agree on the ciphersuite used. It gives more meaning to statements like "Each MLS session uses a single ciphersuite".
 > 
 > Also, it prevents the following attack: the adversary (a malicious insider) invites someone and convinces them that the group uses a ciphersuite with say a signature scheme that is weaker but still compatible with the one actually used. Now the new member uses a weaker scheme and the adversary can impersonate them.

**Comment by franziskuskiefer** [comment]
- [ ] Welcome message validation: Verify that the `cipher_suite` in the GroupInfo matches the `cipher_suite` in the KeyPackage.
- [ ] Add `ProtocolVersion version = mls10` and `CipherSuite cipher_suite` to `GroupContext`
- [ ] Everything else needs to be done together with #719
