### ISSUE TITLE
[MLS Spec change] Use C-style comments in TLS presentation syntax (#745)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#975]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/745

**Description of the changes**
> Fixes #742

**Comment by duesee** [comment]
This is more of an editorial change.

The only thing we can change in the OpenMLS codebase is ...

```diff
struct {
    GroupContext group_context;
    Extension extensions<V>;
    MAC confirmation_tag;
    uint32 signer;
-    // SignWithLabel(., "GroupInfoTBS", GroupInfoTBS)
+    /* SignWithLabel(., "GroupInfoTBS", GroupInfoTBS) */
    opaque signature<V>;
} GroupInfo;
```

Let's do that quickly and close this.
