### ISSUE TITLE
[MLS Spec change] Add ciphersuite field to `PublicGroupStateTBS` (#501)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#982]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/501

**Description of the changes**
> Fixes #498.

**Comment by franziskuskiefer** [comment]
`PublicGroupStateTBS` is removed in [mlswg #529](https://github.com/mlswg/mls-protocol/pull/529/) (#719)
