### ISSUE TITLE
[MLS Spec change] Be explicit that Credentials can attest to multiple identities (#509)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#984]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/509

**Description of the changes**
> The specification currently assumes that a Credential provides a singular identity for a client, when in reality that is not the case.  For example, X509Credential can provide a whole collection of identities, and it's up to the application to decide if its preferred identity is among them.  Just like in TLS, a server can send a cert with 100 domains, but the TLS client knows which one it's looking for.
 > 
 > This PR refactors the parts of the spec that refer to identity to be consistent with this idea.  The main impacts are to processing of Update and Remove-within-External-Commit, both cases in which you want the new KeyPackage to logically represent the same identity as the old one.
 > 
 > This PR also removes the `endpoint_id` field from KeyPackage.  Since we now reference KeyPackages by KeyPackageID, there's no longer a need for a separate identifier.  (Unless we want an identifier that's stable across epochs, but (a) it's not clear to me that that is needed in general and (b) it can easily be added in an extension, as in fact we have done in Webex.)

- [ ] #984

**Comment by nomaxg** [comment]
I'd be happy to take a stab at this!

**Comment by nomaxg** [comment]
Hey @kkohbrok, I've been looking through this and it appears that the protocol changes introduced here have been overwritten by https://github.com/mlswg/mls-protocol/pull/573/files and https://github.com/mlswg/mls-protocol/pull/575/files, so I'm not sure what action items we have here. Let me know if I'm missing something!

**Comment by kkohbrok** [comment]
I think you're right. This PR punts some most of the identity validation work to the application, so from a library standpoint, there is not much to do here. 

Thanks for investigating this @nomaxg! I'll close this for the time being and instead add a comment to #133 so that we don't lose track of the fact that the application needs to validate identity changes. At the very least that should be documented very clearly in the book.
