### ISSUE TITLE
[MLS Spec change] Remove the requirement for Add in external commit (#511)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#986]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/511

**Description of the changes**
> Fixes #505

**Comment by duesee** [comment]
Already implemented via ValSem242?

**Comment by franziskuskiefer** [comment]
Looks like ValSem242 only covers inline proposals?

**Comment by duesee** [comment]
Hm... Maybe I'm getting something wrong but from my understanding external commits can't contain non-inline, i.e., "referenced" proposals?

> In principle, External Commits work like regular Commits. However, their content has to meet a specific set of requirements:
> [...]
> * The Commit MUST NOT include any proposals by reference, since an external joiner cannot determine the validity of proposals sent within the group

Thus, assuming that ValSem242 is in place, that should be it? Of course, I could recheck that ValSem242 does waht it does. Also, maybe we should drop the "inline" for external commits?

**Comment by duesee** [comment]
Btw., for me, it is now not clear if there was another PR enforcing inline proposals. Can I, in situations like that, assume that there was a PR disallowing referenced proposals and that there must have been a spec change issue for that? So, basically, "trust" that our spec change process works?

**Comment by duesee** [comment]
ValSem242 says that ...

> External Commit must not cover any inline Add proposals

Thus, Franziskus remarked (rightfully) that ValSem242 only covers *inline* proposals implying that there could be a referenced Add proposal in the external commit. However, as you say, there is #817.

So, basically, what we I think we should do is to remove the "inline" from all ValSems covering external commits and remark that "inline" is implied by "external commit".

**Comment by duesee** [comment]
There is a working test for `ValSem242` that covers inline Add proposals (but not referenced Add proposals.) Thus, I think we can close this issue or link to #817.

**Comment by franziskuskiefer** [comment]
I commented on #817 with the infos from here and marked @duesee for review on the PR to have a look this.
