### ISSUE TITLE
[MLS Spec change] Generalize tree extend/truncate algorithms (#522)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#994]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/522

**Description of the changes**
> This PR builds on #507 and #521.  It adds the following:
 > 
 > * An explicit note in `Ratchet Tree Terminology` that implementations may use any representation
 > * A general description of how nodes are added to / removed from the tree
 > * Specific algorithms for "array-based trees" and "link-based trees"
 > 
 > (I also made a few minor editorial revisions.)
 > 
 > TWal franziskuskiefer - I think this hits the right balance of specificity and generality.  Interested in your thoughts here.

**Comment by kkohbrok** [comment]
As far as I can tell, this was fixed by #1249.
