### ISSUE TITLE
[MLS Spec change] Downgrade MUST to SHOULD for commit senders including all valid commits (#546)

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#999]
**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/546

**Description of the changes**
> Addresses the comments in ( Resolves #542 )
 > 
 > Since a member performing a commit including all valid proposals within an epoch is best effort, it makes sense to downgrade the requirement from MUST to SHOULD. 
 > 
 > IMO, MUST should be reserved for instances where the receiver would throw an error in the condition the sender did not 100% comply with the rule. Since in this case it is not a hard error under certain conditions, such as the member performing the commit having not received a proposal in transit while generating the commit, SHOULD is a better choice.

**Comment by augustocdias** [comment]
Can you assign this to me please?
